# Generated by Django 4.0.5 on 2022-06-19 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_remove_admin_confirm_password_remove_admin_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
