# Generated by Django 4.0.5 on 2022-06-19 12:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0010_remove_admin_confirm_password_remove_admin_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='hood_image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
    ]
