# Generated by Django 4.0.5 on 2022-06-20 05:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0012_alter_user_neighbourhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_snap_pic',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
    ]
