# Generated by Django 4.0.5 on 2022-06-20 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0013_business_business_snap_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='neighbourhood',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='hood.neighbourhood'),
        ),
    ]
